services:
  - type: web
    name: dashbordsupermarket-backend
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: "python server.py"
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8787"

